### PR TITLE
edit README.md with more run for dev instructions

### PR DESCRIPTION
**Pull request by cy**
took me a while to figure out, thought I'd update the readme to help anyone else out.

### CODE REVIEW

**Comment by jessamynsmith** [comment]
I agree it's a good idea to document the possible environment variables. I'll add that.

You don't normally need to run collectstatic when you're using runserver. Were you seeing some error without it?

**Comment by cy** [comment]
yes, all GETs to static files was 404 or 403ing

```
[Errno 2] No such file or directory: 'staticfiles/css/base.css'
[Errno 2] No such file or directory: 'staticfiles/periods/js/calendar.js'
[Errno 2] No such file or directory: 'staticfiles/periods/css/calendar.css'
[Errno 2] No such file or directory: 'staticfiles/img/logo.png'
[23/Jul/2016 04:33:59] "GET /static/periods/js/calendar.js HTTP/1.1" 404 13
[23/Jul/2016 04:33:59] "GET /static/css/base.css HTTP/1.1" 404 13
[23/Jul/2016 04:33:59] "GET /static/img/logo.png HTTP/1.1" 404 13
[23/Jul/2016 04:33:59] "GET /static/periods/css/calendar.css HTTP/1.1" 404 13
```
etc

**Comment by jessamynsmith** [comment]
I wonder what is different between your system on mine. I have not done collectstatic, and I see:

```
[23/Jul/2016 04:43:11] "GET /static/css/base.css HTTP/1.1" 200 1111
[23/Jul/2016 04:43:11] "GET /static/img/logo.png HTTP/1.1" 200 2971
```

**Comment by jessamynsmith** [comment]
What happens if you completely remove the staticfiles directory and run again?

**Comment by cy** [comment]
still 404s :(, not sure what's different either. I dropped into a debugger here https://github.com/jessamynsmith/eggtimer-server/blob/master/eggtimer/settings.py#L125 and the path inside `STATICFILES_DIRS` is definitely the correct path.

**Comment by jessamynsmith** [comment]
If you go to the admin, do you see the admin static?

**Comment by jessamynsmith** [comment]
I added some info on environment variables, do you think that makes it sufficiently clear? See 976fef9354a5645111f2040358cd90a3b869e894

**Comment by cy** [comment]
That looks great. If I go to the admin, still can't see the static files ;_; Oh well, I'll live with having to do `collectstatic` myself. Thanks for the help!

**Comment by jessamynsmith** [comment]
Would you be willing to do a live session online so I can try to see what's wrong? You can contact me on twitter @jessamynsmith

**Pull request closed without merging**
